### ISSUE TITLE
Needs to be more respect for blocks

### ISSUE THREAD

**Issue by ghost** [daipenger/BauerCam#1]
I love this mod and all, but there needs to be more respect for blocks as it it can be annoying when you are doing cinematics and it keeps glitching into block if in creative or going through when in spectator

**Comment by daipenger** [comment]
Short answer: No, please not

Long answer: You are asking for path finding. This is very hard to implement in this context because I would have to spend countless hours in order to still perserve good looking paths when the path maybe involves 20 obstacles. It would also then disallow the player to fly through glass panes for example. The amount of work for it to happen would be much greater than you just replacing some path points until the path is fixed.

If you have a better solution than path finding, I am open to hear it but I will not implement path finding.
